### ISSUE TITLE
Error in the end of the installation

### ISSUE THREAD

**Issue by amauridimaia** [HighTeckMan/AlexaPi#1]
I get this error at the end of the installation process:

Processing triggers for systemd (215-17+deb8u5) ...
Downloading/unpacking Wave>=0.0.2 (from -r requirements.txt (line 1))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
    req, link, "connection error: %s" % exc, url,
TypeError: __str__ returned non-string (type SysCallError)

after that when I try $ python main.py:
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from memcache import Client
ImportError: No module named memcache

**Comment by lakshay257** [comment]
Iyyyyuiyiyyyyyyy
